### ISSUE TITLE
Device types

### ISSUE THREAD

**Issue by antonygk** [myroom/homebridge-sonoff-mini-api-rest#2]
Hello, I’m trying to change the lightbulb device type on homebridge and Apple’s Home app with no success. The only device types that I can select is for lighting. Could you please release an update to let me do that?

**Comment by zhekahome** [comment]
Эта проблема тоже волнует. У меня не только свет включается этими устройствами, а и вентиляторы, насосы, да что угодно. Почему картинка только свет. Сделайте возможность выбора.

**Comment by myroom** [comment]
Удалось добавить вентилятор. Насосы и прочее к сожалению не поддерживаются. Homebridge

**Comment by 0ldF0x** [comment]
I've created a pull request for this issue.
