### ISSUE TITLE
Latest version (1.1.3) breaks sonoff DIY

### ISSUE THREAD

**Issue by alladinian** [myroom/homebridge-sonoff-mini-api-rest#3]
Hi there. 
After upgrading to version 1.1.3 I get this error in the logs and the accessory cannot be controlled anymore:

`Error getting state (status code undefined): getaddrinfo ENOTFOUND undefined`

after downgrading to v1.0.5 everything is back to normal again...

**Comment by myroom** [comment]
sorry.  correct the variable in the config uri -> url

**Comment by myroom** [comment]
or just remove and re-add devices

**Comment by alladinian** [comment]
Thanks. 
That would be the problem.
As a suggestion, maybe it would be a good idea (at least for a few versions) to look also for `uri` (maybe with a deprecation notice) before dropping it to maintain backwards compatibility.

**Comment by myroom** [comment]
Thank. Fixed;)
