### ISSUE TITLE
uri/url issue

### ISSUE THREAD

**Issue by neilheyes** [myroom/homebridge-sonoff-mini-api-rest#5]
Hi,

I noticed the code doesn't work to try and use the old config.  you have to change the code config to url to get the new version to work.

**Comment by neilheyes** [comment]
Hi,

If you change the code to:

  // old version config
  if(this.url === undefined) {
    this.url = config["uri"];
  }

it works.

N

**Comment by myroom** [comment]
Hi

thank you very much, corrected)

> 8 мая 2020 г., в 20:57, neilheyes <notifications@github.com> написал(а):
> 
> if(this.url === undefined) {
> this.url = config["uri"];
> }

**Comment by neilheyes** [comment]
super.  Installed and working.

**Comment by myroom** [comment]
fixed
