### ISSUE TITLE
Getting current state...  SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by MarkARushton** [myroom/homebridge-sonoff-mini-api-rest#6]
Hello, Just installed this plugin but getting the following error in the logs, any thoughts?

`[5/27/2020, 14:00:44] [Mark Bedroom Relay] Getting current state...
[5/27/2020, 14:00:45] SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at fn (/usr/lib/node_modules/homebridge-sonoff-mini-api-rest/index.js:46:24)
    at Request.callback (/usr/lib/node_modules/homebridge-sonoff-mini-api-rest/node_modules/superagent/src/node/index.js:878:12)
    at fn (/usr/lib/node_modules/homebridge-sonoff-mini-api-rest/node_modules/superagent/src/node/index.js:1117:18)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-sonoff-mini-api-rest/node_modules/superagent/src/node/parsers/json.js:19:7)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)`

**Comment by diegoves** [comment]
hello! same issue, did you resolve?

**Comment by myroom** [comment]
Hello! Send me your config file.

**Comment by myroom** [comment]
Hello! Send me your config file.

**Comment by diegoves** [comment]
this is the config file: 
{
    "bridge": {
        "name": "Homebridge 1769",
        "username": "XXXXXX",
        "port": 51883,
        "pin": "XXXXXX"
    },
    "accessories": [
        {
            "accessory": "Sonoff",
            "type": "lightbulb",
            "name": "Cucina",
            "url": "http://192.168.1.162:8081",
            "id": "1000b5820d",
            "debug": true 
        }
    ],
    "platforms": []
}

**Comment by myroom** [comment]
The config is fine. What is your firmware version on your sonoff? And what type of sonoff?

**Comment by diegoves** [comment]
SONOFF mini wi-fi diy with firmware 3.5.0, the latest.

**Comment by diegoves** [comment]
I found the bug: you have to change two line in your index.js file:

the line 57 from this
var state = JSON.parse(json).switch;
to this: 
var state = JSON.parse(response.text).data.switch;

and the line 60 from this: 
this.log('getState() request returned successfully ('+response.statusCode+'). Body: '+JSON.stringify(json));
to this: 
this.log('getState() request returned successfully ('+response.statusCode+'). Body: '+response.text);

**Comment by 0ldF0x** [comment]
I've created a pull request for this issue.

**Comment by frpastor** [comment]
Hi all, thanks to @myroom for delivering such superb piece of SW. Tried it out and with the fix provided by @Diegoves worked correctly. However I have a question, if you press the external rocket switch connected to the Sonoff mini DIY, Homebridge doesn't notice it and still shows up the old status. Same happens in the "Home" app for IOS, the accessory remains in its previous status even if you activate manually the physical switch. Is there any "polling" interval we can adjust?

**Comment by myroom** [comment]
> I found the bug: you have to change two line in your index.js file:
> 
> the line 57 from this
> var state = JSON.parse(json).switch;
> to this:
> var state = JSON.parse(response.text).data.switch;
> 
> and the line 60 from this:
> this.log('getState() request returned successfully ('+response.statusCode+'). Body: '+JSON.stringify(json));
> to this:
> this.log('getState() request returned successfully ('+response.statusCode+'). Body: '+response.text);

fixed

**Comment by frpastor** [comment]
Thanks a lot, I made the changes and restarted the HB service and now it works correctly!

Great work, Will use it with more Sonoff Minis I just purchased.
